### PR TITLE
My shot at the proportional valve controller

### PR DESCRIPTION
**Pull request by JessieAMorris**
Here's my attempt at the proportional valve controller logic. I don't have an arduino and the buttons and such handy, so I can't easily test it.

### CODE REVIEW

**Comment by Bumblefuck** [comment]
Ok I merged the other one, but I like the idea of no libraries. So I can leave this pull request and try it out and merge it later despite the "branch conflicts", right?

**Comment by queuetue** [comment]
@JessieAMorris can merge master back into his branch and fix the conflicts.  Then when he pushes, it will automatically make this pull request "go green".

**Comment by JessieAMorris** [comment]
Yeah, I'll take care of that later today. I would probably suggest the easiest way to try out the two different options would be to have two different branches that you can switch between. That way you can toggle back and forth pretty easily.

**Comment by JessieAMorris** [comment]
I can go ahead and close this then.

**Pull request closed without merging**
