### PR TITLE
Added comments to previous code & fixed small errors

### PR DESCRIPTION
**Pull request by ItKindaWorks**
I added comments to DanNixon's code (or at least my understanding of what his code does) and fixed some mistakes in that code. 

Most notably I made the analogWrite values forced to be absolute values so we dont write negative PWM values. 

I also forced the joystick axis values to be constrained to within -255 to 255 (absolute val of 0-255) which is our maximum analog write range. This may not  be needed if the joystick is calibrated correctly however in my test hardware, I have 2 linear pots reading from 0-1023 which the code is not calibrated for.

I also made the debug serial printing of joystick values a bit cleaner.

### CODE REVIEW

**Comment by JessieAMorris** [comment]
All of the pots will read 0-1023, that's how the [analog read](https://www.arduino.cc/en/Reference/AnalogRead) works.

I created a different pull request that I feel is a little cleaner and better organized, but it doesn't use a lot of the built in Ardunio libraries cause I'm thinking C not Arduino. :-P

**Comment by Bumblefuck** [comment]
I'll have a go with this code next week with some pots. Should I pull the
trigger on buying that nice joystick?

**Comment by JessieAMorris** [comment]
I'd suggest rocking the potentiometer and the buttons to start with. Why complicate things right at the get go? Buttons are simple, off and on.

**Comment by Bumblefuck** [comment]
Machining brackets currently... :) Thank you very, very much!
Can I ask you candidly what I should do for a kickback for this and future
coding projects. Like should I just flat out pay an hourly rate, but what
about guys who submit code that's already been done by somebody else.
Should I just send out swag (not that I have any) or just have a set
"here's a cool hundy for beers, Cheers!"

Hey wait, I'm I replying to an automated message?

**Comment by JessieAMorris** [comment]
That's hard to say. Personally I'd be cool with just a shout out in the videos and maybe an AVE mug or something. Or maybe have a different give away pool for people that have assisted in some way or another? What do you do for people that send you gear?

**Comment by Bumblefuck** [comment]
Normally, for gear I'll explain that I don't want freebies and pay them or
if they're adamant I'll just pay it forward. Like somebody sent me an old
DRO for the mill and I am sending some oddball stepper drivers to somebody
else. But isn't there some normal arrangement like "code for beers". If not
somebody should set that up, or at least try it out to see if it works.
Hmmmm....

**Comment by ItKindaWorks** [comment]
I'm just happy to help personally. You're videos are awesome and I've been spreading the word to all of my other engineer friends. All I could possibly ask for is a shoutout to my YT channel (https://www.youtube.com/channel/UCOnMlI1Si4i0O2Wkz-XReww) at some point. But really I'm just happy to help out.

**Comment by ItKindaWorks** [comment]
I'm currently just using 2 pots. If you'd like to go in that direction rather than going with the joystick right off the bat, the only thing I have to suggest is changing the calibration values to use the whole 0-1023 range. Make sure you have linear pots though not logarithmic.

I also started working on a local branch that changes the joystick from pots to just 4 buttons (like an old arcade joystick) and a speed control pot which is what I think you were saying originally in the video. If you'd like to go that route, I can clean that up and push it.

**Comment by JessieAMorris** [comment]
The pull request I made does just that, 4 buttons and a speed control pot. I’d love to see the differences between the two.

—
Jessie A. Morris
jessie@jessieamorris.com

**Comment by ItKindaWorks** [comment]
Oh ok cool. I honestly haven't finished making look ok. It looks different from yours but only because I was trying to use DanNixon's libraries since that seemed to be the starting point. If I were to have written it without the lib, I would have done something similar. If we do want to go in the button-joystick direction, your code is probably the simplest because theres no real need for DanNixon's library other than it was the first.

**Comment by DanNixon** [comment]
The only reason I wrote that library was to stop me having to write almost identical input processing code in multiple projects, I think this is a lot cleaner than what I used to use (although I wrote it so I would say that).

If I had to make a case for my implementation its that ti does not have a blocking `loop()`, with mine you could add additional processing/feedback to `loop()` and it would continue to work.

**Comment by ItKindaWorks** [comment]
I hope you didn't take my comments as disliking your library, after looking at it last night to get a feel for what you wrote, I think it's a great library to keep around and honestly I was looking into getting some of those joysticks because the lib makes it easy to calibrate and actually setup motion control rather than just analog reading and going from there. And I was also very pleased with the non-blocking loop - something that really should be taught from the get-go especially with embedded programming.

It's up to AvE though which way he wants to go. I think some sort of amalgamation of the two current pull requests would be the best solution at some point probably. Dan, yours/my additions are well suited for pot joysticks and could easily be modified for buttons but doesnt include the ramping so it's up to the stick operator to not throw it to full and cause jerky motion. And Jessie, yours is all setup for a button joystick and has nice ramping but doesnt have the pot joystick.

**Comment by Bumblefuck** [comment]
Non blocking loop? Jeeze fellas, I'm just gonna go stand in the broom
closet. I'm glad you guys are on it!

Who's taking point? I'm out of my depth.
Admin stuff: how much should I budget for you guys. The channel can pay for
any hardware, grease, beer, etc... If/when there are any hangups. Let's do
this!

**Comment by DanNixon** [comment]
@ItKindaWorks Don't worry I wasn't taking offence.
It would be easy to add ramping to what I already have.

@Bumblefuck Beer funds is good for me!

**Comment by ItKindaWorks** [comment]
@DanNixon Unless your lib has ramping built in somewhere, maybe I'll try merging yours/mine together with @JessieAMorris ramping code. 

@Bumblefuck Like I said, a shoutout to my channel is all I really want but I also enjoy beers if the shoutout isn't enough for you. Also do you which way are you leaning at the moment, button joystick with speed control knob or a pot joystick? It's not too hard to do either but we should probably pick a direction before we get too far into it.

**Comment by DanNixon** [comment]
@ItKindaWorks It doesn't, it could be added by subclassing `IValueTransform`, but this would only work with analog input devices.

The best way would be to have the ramping code have a target value and keep it separate from the input code.

The ramping would probably be better off implemented as smoothing that runs continuously in order to limit the maximum rate of change, rather than just linearly stepping an value (assuming I properly understand the reason for it in the first place).

**Comment by ItKindaWorks** [comment]
My idea was to more or less use the stick reading as a target value and then use @JessieAMorris's ramping technique and ramp from whatever the current rate is up/down to the desired rate from the stick. That way, the stick gives the "max" speed in a given direction and the speed is slowly changed to match the target. Each time through the loop the ramp function can be called generating a new change since last loop.

I'll be honest, this is one of the first times I've had to git more than my own local repos so I don't know the most elegant way to take each of your code and make a new version from them besides just taking your files and editing the current code to do what we've been talking about and creating a new pull request from that. Is there a better way than just doing that?

**Comment by DanNixon** [comment]
@ItKindaWorks Not really, the most correct way is to merge one branch into another, this will fail and ask you to merge manually, at this point you start working on integrating them.

This is not much different from taking the code of the second and adding it to the first, but the merge commit in the history gives an indication as to what you were actually doing.

**Comment by ItKindaWorks** [comment]
Ok cool, I'll try tomorrow probably and see how it goes merging the two together!

**Comment by JessieAMorris** [comment]
Sounds good guys. I am elbow deep in a car project this weekend so I probably won't have a chance to assist any more till Monday. 

On April 9, 2016 2:50:57 PM MDT, ItKindaWorks <notifications@github.com> wrote:
>Ok cool, I'll try tomorrow probably and see how it goes merging the two
>together!
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Bumblefuck/HBR-Proportional-Valve/pull/2#issuecomment-207852363

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Bumblefuck** [comment]
in answer to button and pot or joystick pot: button and pot for now and
joystick pot for funsies later. My main concern is controlling speed as
well as smooth accel/decel. Large mass steel fabrications have lots of slop
and vibe issues, couple that with stop/go hydraulics and you get a
unpredictable machine. The beauty of using a proportional valve is the
ability to dampen via software (but that's a long way off).

**Comment by ItKindaWorks** [comment]
In that case, I think you might as well go with @JessieAMorris code to start with as it's already setup for that and let us know what works/doesn't work as you test things out. I'm happy to keep working at merging @JessieAMorris's code with this code if you think you'll want the pot joystick in the future though.

**Pull request merged**
